#!/usr/bin/env node
// PIX token build — one source (src/pix.tokens.json), every platform.
// Zero dependencies: resolves aliases per theme, then writes
// CSS, SCSS, JS/TS, JSON, iOS (Swift), Android (XML + Compose), Flutter and React Native.
import { readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = JSON.parse(readFileSync(join(here, "src/pix.tokens.json"), "utf8"));
const out = join(here, "dist");
rmSync(out, { recursive: true, force: true });
const write = (p, s) => { const f = join(out, p); mkdirSync(dirname(f), { recursive: true }); writeFileSync(f, s); };
const HEADER = "Generated by @pix-ui/tokens — do not edit. Source: src/pix.tokens.json";

// ---------- resolve colours per theme ----------
const themes = src.color.themes.map((t) => t.id); // ["light","dark"]
const primary = themes[0];
const raw = new Map(src.color.tokens.map((t) => [t.name, t]));
const valueIn = (tok, theme) => (typeof tok.value === "string" ? tok.value : tok.value[theme] ?? tok.value[primary]);
function resolve(name, theme, seen = new Set()) {
  if (seen.has(name)) throw new Error(`alias cycle at ${name}`);
  seen.add(name);
  const tok = raw.get(name);
  if (!tok) throw new Error(`unknown colour token ${name}`);
  const v = valueIn(tok, theme);
  const m = /^\{(.+)\}$/.exec(v);
  return m ? resolve(m[1], theme, seen) : v;
}
const colors = Object.fromEntries(themes.map((th) => [th, Object.fromEntries([...raw.keys()].map((n) => [n, resolve(n, th)]))]));

function rgba(v) {
  let m = /^#([0-9a-f]{3,8})$/i.exec(v);
  if (m) {
    let h = m[1];
    if (h.length <= 4) h = [...h].map((c) => c + c).join("");
    const n = (i) => parseInt(h.slice(i, i + 2), 16);
    return { r: n(0), g: n(2), b: n(4), a: h.length === 8 ? n(6) / 255 : 1 };
  }
  m = /^rgba?\(\s*([\d.]+)[\s,]+([\d.]+)[\s,]+([\d.]+)\s*(?:[/,]\s*([\d.]+%?))?\s*\)$/.exec(v);
  if (m) {
    let a = m[4] === undefined ? 1 : m[4].endsWith("%") ? parseFloat(m[4]) / 100 : parseFloat(m[4]);
    return { r: +m[1], g: +m[2], b: +m[3], a };
  }
  throw new Error(`unsupported colour ${v}`);
}
const hex2 = (n) => Math.round(n).toString(16).padStart(2, "0");
const argbHex = ({ r, g, b, a }) => `${hex2(a * 255)}${hex2(r)}${hex2(g)}${hex2(b)}`.toUpperCase();
const round = (n) => Math.round(n * 1000) / 1000;

// ---------- scalar families ----------
const fam = (k) => (src[k]?.tokens ?? []);
const px = (v) => (typeof v === "number" ? v : /px$/.test(v) ? parseFloat(v) : v === "0" ? 0 : /rem$/.test(v) ? parseFloat(v) * 16 : parseFloat(v));
const ms = (v) => parseFloat(v);
const scalar = {
  space: fam("spacing"), radius: fam("radius"), shadow: fam("shadow"), motion: fam("motion"),
  fontSize: fam("fontSize"), lineHeight: fam("lineHeight"), fontWeight: fam("fontWeight"), fontFamily: fam("fontFamily"),
};
const typeStyles = (src.type?.groups ?? []).flatMap((g) => g.styles).map((s) => ({
  name: s.name, fontSize: s.fontSize, lineHeight: s.lineHeight, fontWeight: s.fontWeight ?? "400", letterSpacing: s.letterSpacing ?? "0",
}));

// camelCase / identifier helpers
const camel = (s) => s.replace(/[-.](\w)/g, (_, c) => c.toUpperCase()).replace(/^(\d)/, "x$1");
const snake = (s) => s.replace(/[-.]/g, "_");

// ============ CSS ============
const cssBlock = (sel, map) => `${sel} {\n${Object.entries(map).map(([k, v]) => `  --${k}: ${v};`).join("\n")}\n}\n`;
const darkDiff = Object.fromEntries(Object.entries(colors.dark).filter(([k, v]) => v !== colors[primary][k]));
const scalarCss = Object.fromEntries(Object.values(scalar).flat().map((t) => [t.name, t.value]));
const tokensCss =
  `/* ${HEADER} */\n` +
  cssBlock(':root, [data-theme="light"]', colors[primary]) +
  cssBlock('[data-theme="dark"], .dark', darkDiff) +
  cssBlock(":root", scalarCss);
write("css/tokens.css", tokensCss);
write("css/tokens.auto-dark.css",
  `/* ${HEADER} — follows the OS colour scheme unless data-theme="light" is set */\n` +
  cssBlock(':root, [data-theme="light"]', colors[primary]) +
  `@media (prefers-color-scheme: dark) {\n${cssBlock(':root:not([data-theme="light"])', darkDiff).replace(/^/gm, "  ")}}\n` +
  cssBlock('[data-theme="dark"], .dark', darkDiff) + cssBlock(":root", scalarCss));

// ============ SCSS ============
write("scss/_tokens.scss",
  `// ${HEADER}\n` +
  Object.entries(colors[primary]).map(([k, v]) => `$pix-${k}: ${v};`).join("\n") + "\n" +
  Object.entries(colors.dark).map(([k, v]) => `$pix-dark-${k}: ${v};`).join("\n") + "\n" +
  Object.entries(scalarCss).map(([k, v]) => `$pix-${k}: ${/[,"]/.test(v) && !/^\d/.test(v) ? v : v};`).join("\n") + "\n");

// ============ JS / TS ============
const group = (arr, f = (v) => v) => Object.fromEntries(arr.map((t) => [t.name, f(t.value)]));
const js = {
  color: colors,
  space: group(scalar.space), radius: group(scalar.radius), shadow: group(scalar.shadow), motion: group(scalar.motion),
  fontSize: group(scalar.fontSize), lineHeight: group(scalar.lineHeight), fontWeight: group(scalar.fontWeight),
  fontFamily: group(scalar.fontFamily), typography: Object.fromEntries(typeStyles.map((s) => [s.name, s])),
};
const cssVar = Object.fromEntries([...raw.keys(), ...Object.keys(scalarCss)].map((k) => [k, `var(--${k})`]));
const jsBody = `export const tokens = ${JSON.stringify(js, null, 2)};\nexport const cssVar = ${JSON.stringify(cssVar, null, 2)};\nexport default tokens;\n`;
write("js/index.js", `// ${HEADER}\n${jsBody}`);
write("js/index.cjs", `// ${HEADER}\n"use strict";\n${jsBody.replace(/export const (\w+)/g, "const $1").replace("export default tokens;", "module.exports = { tokens, cssVar, default: tokens };")}`);
const colorKeys = [...raw.keys()].map((k) => JSON.stringify(k)).join(" | ");
const keyUnion = (arr) => arr.map((t) => JSON.stringify(t.name)).join(" | ") || "never";
const dts = `// ${HEADER}
export type PixTheme = ${themes.map((t) => JSON.stringify(t)).join(" | ")};
export type PixColorToken = ${colorKeys};
export interface PixTypeStyle { name: string; fontSize: string; lineHeight: string; fontWeight: string; letterSpacing: string }
export interface PixTokens {
  color: Record<PixTheme, Record<PixColorToken, string>>;
  space: Record<${keyUnion(scalar.space)}, string>;
  radius: Record<${keyUnion(scalar.radius)}, string>;
  shadow: Record<${keyUnion(scalar.shadow)}, string>;
  motion: Record<${keyUnion(scalar.motion)}, string>;
  fontSize: Record<${keyUnion(scalar.fontSize)}, string>;
  lineHeight: Record<${keyUnion(scalar.lineHeight)}, string>;
  fontWeight: Record<${keyUnion(scalar.fontWeight)}, string>;
  fontFamily: Record<${keyUnion(scalar.fontFamily)}, string>;
  typography: Record<${keyUnion(typeStyles)}, PixTypeStyle>;
}
export declare const tokens: PixTokens;
export declare const cssVar: Record<string, string>;
export default tokens;
`;
write("js/index.d.ts", dts);
write("js/index.d.cts", dts);
write("json/tokens.json", JSON.stringify(js, null, 2));

// ============ React Native (unitless numbers) ============
const rnColor = (v) => { const c = rgba(v); return c.a === 1 ? v : `rgba(${c.r}, ${c.g}, ${c.b}, ${round(c.a)})`; };
const rn = {
  color: Object.fromEntries(themes.map((th) => [th, Object.fromEntries(Object.entries(colors[th]).map(([k, v]) => [k, rnColor(v)]))])),
  space: group(scalar.space, px), radius: group(scalar.radius, px),
  fontSize: group(scalar.fontSize, px), lineHeight: group(scalar.lineHeight, Number), fontWeight: group(scalar.fontWeight, String),
  duration: Object.fromEntries(scalar.motion.filter((t) => /ms$/.test(t.value)).map((t) => [t.name, ms(t.value)])),
  fontFamily: { sans: "System", mono: "Menlo" },
};
const rnBody = `export const rnTokens = ${JSON.stringify(rn, null, 2)};\nexport default rnTokens;\n`;
write("react-native/index.js", `// ${HEADER}\n${rnBody}`);
write("react-native/index.cjs", `// ${HEADER}\n"use strict";\n${rnBody.replace("export const rnTokens", "const rnTokens").replace("export default rnTokens;", "module.exports = { rnTokens, default: rnTokens };")}`);
const rnDts = `// ${HEADER}
import type { PixTheme, PixColorToken } from "../js/index";
export interface PixRNTokens {
  color: Record<PixTheme, Record<PixColorToken, string>>;
  space: Record<string, number>; radius: Record<string, number>;
  fontSize: Record<string, number>; lineHeight: Record<string, number>;
  fontWeight: Record<string, "100"|"200"|"300"|"400"|"500"|"600"|"700"|"800"|"900">;
  duration: Record<string, number>; fontFamily: { sans: string; mono: string };
}
export declare const rnTokens: PixRNTokens;
export default rnTokens;
`;
write("react-native/index.d.ts", rnDts);
write("react-native/index.d.cts", rnDts);

// ============ iOS (Swift, dynamic light/dark) ============
const swiftColor = (v) => { const c = rgba(v); return `UIColor(red: ${round(c.r / 255)}, green: ${round(c.g / 255)}, blue: ${round(c.b / 255)}, alpha: ${round(c.a)})`; };
write("ios/PixTokens.swift", `// ${HEADER}
import UIKit
#if canImport(SwiftUI)
import SwiftUI
#endif

private func pixDynamic(_ light: UIColor, _ dark: UIColor) -> UIColor {
    UIColor { $0.userInterfaceStyle == .dark ? dark : light }
}

public enum PixColor {
${[...raw.keys()].map((k) => `    public static let ${camel(k)} = pixDynamic(${swiftColor(colors[primary][k])}, ${swiftColor(colors.dark[k])})`).join("\n")}
}

#if canImport(SwiftUI)
@available(iOS 13.0, macOS 10.15, *)
public extension Color {
    enum Pix {
${[...raw.keys()].map((k) => `        public static let ${camel(k)} = Color(PixColor.${camel(k)})`).join("\n")}
    }
}
#endif

public enum PixSpace {
${scalar.space.map((t) => `    public static let ${camel(t.name.replace(/^space-/, "s"))}: CGFloat = ${px(t.value)}`).join("\n")}
}

public enum PixRadius {
${scalar.radius.map((t) => `    public static let ${camel(t.name.replace(/^radius-/, ""))}: CGFloat = ${px(t.value)}`).join("\n")}
}

public enum PixFontSize {
${scalar.fontSize.map((t) => `    public static let ${camel(t.name.replace(/^text-/, ""))}: CGFloat = ${px(t.value)}`).join("\n")}
}

public enum PixDuration {
${scalar.motion.filter((t) => /ms$/.test(t.value)).map((t) => `    public static let ${camel(t.name.replace(/^dur-/, ""))}: TimeInterval = ${ms(t.value) / 1000}`).join("\n")}
}
`);

// ============ Android XML ============
const xmlColors = (th) => `<?xml version="1.0" encoding="utf-8"?>\n<!-- ${HEADER} -->\n<resources>\n${Object.entries(colors[th]).map(([k, v]) => `    <color name="pix_${snake(k)}">#${argbHex(rgba(v))}</color>`).join("\n")}\n</resources>\n`;
write("android/values/pix_colors.xml", xmlColors(primary));
write("android/values-night/pix_colors.xml", xmlColors("dark"));
write("android/values/pix_dimens.xml", `<?xml version="1.0" encoding="utf-8"?>\n<!-- ${HEADER} -->\n<resources>\n${[
  ...scalar.space.map((t) => `    <dimen name="pix_${snake(t.name)}">${px(t.value)}dp</dimen>`),
  ...scalar.radius.map((t) => `    <dimen name="pix_${snake(t.name)}">${Math.min(px(t.value), 9999)}dp</dimen>`),
  ...scalar.fontSize.map((t) => `    <dimen name="pix_${snake(t.name)}">${px(t.value)}sp</dimen>`),
].join("\n")}\n</resources>\n`);

// ============ Jetpack Compose ============
const kColor = (v) => `Color(0x${argbHex(rgba(v))})`;
write("compose/PixTokens.kt", `// ${HEADER}
package dev.pixui.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

data class PixColors(
${[...raw.keys()].map((k) => `    val ${camel(k)}: Color,`).join("\n")}
)

val PixLightColors = PixColors(
${[...raw.keys()].map((k) => `    ${camel(k)} = ${kColor(colors[primary][k])},`).join("\n")}
)

val PixDarkColors = PixColors(
${[...raw.keys()].map((k) => `    ${camel(k)} = ${kColor(colors.dark[k])},`).join("\n")}
)

object PixSpace {
${scalar.space.map((t) => `    val ${camel(t.name.replace(/^space-/, "s"))} = ${px(t.value)}.dp`).join("\n")}
}

object PixRadius {
${scalar.radius.map((t) => `    val ${camel(t.name.replace(/^radius-/, ""))} = ${Math.min(px(t.value), 9999)}.dp`).join("\n")}
}

object PixFontSize {
${scalar.fontSize.map((t) => `    val ${camel(t.name.replace(/^text-/, ""))} = ${px(t.value)}.sp`).join("\n")}
}
`);

// ============ Flutter ============
const dColor = (v) => `Color(0x${argbHex(rgba(v))})`;
write("flutter/pix_tokens.dart", `// ${HEADER}
import 'package:flutter/painting.dart';

class PixColors {
  const PixColors({
${[...raw.keys()].map((k) => `    required this.${camel(k)},`).join("\n")}
  });
${[...raw.keys()].map((k) => `  final Color ${camel(k)};`).join("\n")}

  static const light = PixColors(
${[...raw.keys()].map((k) => `    ${camel(k)}: ${dColor(colors[primary][k])},`).join("\n")}
  );

  static const dark = PixColors(
${[...raw.keys()].map((k) => `    ${camel(k)}: ${dColor(colors.dark[k])},`).join("\n")}
  );
}

class PixSpace {
${scalar.space.map((t) => `  static const double ${camel(t.name.replace(/^space-/, "s"))} = ${px(t.value)};`).join("\n")}
}

class PixRadius {
${scalar.radius.map((t) => `  static const double ${camel(t.name.replace(/^radius-/, ""))} = ${Math.min(px(t.value), 9999)};`).join("\n")}
}

class PixFontSize {
${scalar.fontSize.map((t) => `  static const double ${camel(t.name.replace(/^text-/, ""))} = ${px(t.value)};`).join("\n")}
}
`);

console.log(`@pix-ui/tokens: ${raw.size} colours × ${themes.length} themes, ${Object.keys(scalarCss).length} scalar tokens → dist/{css,scss,js,json,react-native,ios,android,compose,flutter}`);
