import { AuditLog } from "@pix-ui/react";

const events = [
  {
    id: "evt_7f2a1c",
    ts: "2026-01-14T07:12:03Z",
    message: "Approved invoice payment within policy limit",
    agent: "AP-Resolver",
    identity: "svc-ap-resolver@prod",
    kind: "decision",
    system: "SAP S/4HANA",
    resource: "invoice:INV-88213",
    action: "approve_payment",
    outcome: "ok",
    entity: "vendor:acme-corp",
    control: "SOD-04",
    run_id: "run_4471",
    trace_id: "trace_9a21",
    latency_ms: 182,
    rationale:
      "Amount $4,200 is under the $10,000 auto-approval limit and the vendor is on the approved list.",
  },
  {
    id: "evt_3b9d44",
    ts: "2026-01-14T08:03:41Z",
    message: "Read vendor master record",
    agent: "AP-Resolver",
    identity: "svc-ap-resolver@prod",
    kind: "read",
    system: "SAP S/4HANA",
    resource: "vendor:acme-corp",
    action: "get_vendor",
    outcome: "ok",
    entity: "vendor:acme-corp",
    run_id: "run_4471",
    trace_id: "trace_9a21",
    latency_ms: 64,
  },
  {
    id: "evt_c01e92",
    ts: "2026-01-14T09:21:55Z",
    message: "Updated bank details on vendor record outside business hours",
    agent: "AP-Resolver",
    identity: "svc-ap-resolver@prod",
    kind: "write",
    system: "SAP S/4HANA",
    resource: "vendor:globex",
    action: "update_bank_details",
    outcome: "flagged",
    entity: "vendor:globex",
    control: "SOD-04",
    run_id: "run_4482",
    trace_id: "trace_0c13",
    latency_ms: 210,
  },
  {
    id: "evt_55aa10",
    ts: "2026-01-14T09:22:40Z",
    message: "Escalated bank detail change for manual review",
    agent: "AP-Resolver",
    identity: "svc-ap-resolver@prod",
    kind: "escalation",
    system: "SAP S/4HANA",
    resource: "vendor:globex",
    action: "escalate",
    outcome: "ok",
    entity: "vendor:globex",
    control: "SOD-04",
    run_id: "run_4482",
    trace_id: "trace_0c13",
    latency_ms: 44,
    rationale:
      "Bank detail changes made outside business hours are routed to a human reviewer regardless of amount.",
  },
  {
    id: "evt_19ef3d",
    ts: "2026-01-14T10:05:12Z",
    message: "Denied access to restricted customer segment",
    agent: "Collections-Agent",
    identity: "svc-collections@prod",
    kind: "auth",
    system: "Salesforce",
    resource: "segment:enterprise-tier-1",
    action: "access_request",
    outcome: "denied",
    entity: "customer:initech",
    control: "ABAC-12",
    run_id: "run_5501",
    trace_id: "trace_7f40",
    latency_ms: 38,
  },
  {
    id: "evt_a2d701",
    ts: "2026-01-14T10:40:28Z",
    message: "Sent dunning email for invoice 30 days overdue",
    agent: "Collections-Agent",
    identity: "svc-collections@prod",
    kind: "tool_call",
    system: "Salesforce",
    resource: "invoice:INV-77410",
    action: "send_email",
    outcome: "ok",
    entity: "customer:initech",
    run_id: "run_5501",
    trace_id: "trace_7f40",
    latency_ms: 310,
  },
  {
    id: "evt_f03b88",
    ts: "2026-01-14T11:15:02Z",
    message: "Queried account balance",
    agent: "Collections-Agent",
    identity: "svc-collections@prod",
    kind: "read",
    system: "Snowflake",
    resource: "table:fct_ar_balances",
    action: "query",
    outcome: "ok",
    entity: "customer:initech",
    run_id: "run_5501",
    trace_id: "trace_7f40",
    latency_ms: 920,
  },
  {
    id: "evt_908cce",
    ts: "2026-01-14T12:02:19Z",
    message: "Login from new device",
    agent: "Access-Reviewer",
    identity: "svc-access-review@prod",
    kind: "auth",
    system: "Okta",
    resource: "user:j.martinez",
    action: "login",
    outcome: "flagged",
    entity: "user:j.martinez",
    control: "AC-07",
    run_id: "run_6010",
    trace_id: "trace_2b88",
    latency_ms: 150,
  },
  {
    id: "evt_1dcb77",
    ts: "2026-01-14T12:48:51Z",
    message: "Revoked standing access after 90-day inactivity",
    agent: "Access-Reviewer",
    identity: "svc-access-review@prod",
    kind: "decision",
    system: "Okta",
    resource: "user:r.chen",
    action: "revoke_access",
    outcome: "ok",
    entity: "user:r.chen",
    control: "AC-02",
    run_id: "run_6031",
    trace_id: "trace_55e1",
    latency_ms: 190,
    rationale:
      "No sign-in or resource access recorded in 90 days; policy requires revocation pending manager re-approval.",
  },
  {
    id: "evt_6a40f5",
    ts: "2026-01-14T13:30:07Z",
    message: "Query timed out against replica",
    agent: "Collections-Agent",
    identity: "svc-collections@prod",
    kind: "tool_call",
    system: "Snowflake",
    resource: "table:fct_ar_balances",
    action: "query",
    outcome: "error",
    entity: "customer:globex",
    run_id: "run_5512",
    trace_id: "trace_9910",
    latency_ms: 4800,
  },
  {
    id: "evt_bb12d9",
    ts: "2026-01-14T14:18:33Z",
    message: "Approved invoice payment within policy limit",
    agent: "AP-Resolver",
    identity: "svc-ap-resolver@prod",
    kind: "decision",
    system: "SAP S/4HANA",
    resource: "invoice:INV-88340",
    action: "approve_payment",
    outcome: "ok",
    entity: "vendor:initech",
    control: "SOD-04",
    run_id: "run_4510",
    trace_id: "trace_3dd2",
    latency_ms: 176,
    rationale:
      "Amount $1,180 is under the $10,000 auto-approval limit and the vendor is on the approved list.",
  },
  {
    id: "evt_e77a21",
    ts: "2026-01-14T15:02:46Z",
    message: "Exported access review report",
    agent: "Access-Reviewer",
    identity: "svc-access-review@prod",
    kind: "read",
    system: "Okta",
    resource: "report:q4-access-review",
    action: "export",
    outcome: "ok",
    entity: "control:AC-02",
    run_id: "run_6040",
    trace_id: "trace_88a0",
    latency_ms: 410,
  },
  {
    id: "evt_cf3301",
    ts: "2026-01-14T15:51:19Z",
    message: "Payment blocked — vendor flagged for sanctions screening",
    agent: "AP-Resolver",
    identity: "svc-ap-resolver@prod",
    kind: "decision",
    system: "SAP S/4HANA",
    resource: "invoice:INV-88355",
    action: "approve_payment",
    outcome: "denied",
    entity: "vendor:northwind",
    control: "SOD-04",
    run_id: "run_4522",
    trace_id: "trace_6611",
    latency_ms: 165,
    rationale:
      "Vendor matched a sanctions watchlist entry pending compliance review; payment held automatically.",
  },
  {
    id: "evt_02be6c",
    ts: "2026-01-14T16:44:02Z",
    message: "Read customer contact record",
    agent: "Collections-Agent",
    identity: "svc-collections@prod",
    kind: "read",
    system: "Salesforce",
    resource: "customer:northwind",
    action: "get_contact",
    outcome: "ok",
    entity: "customer:northwind",
    run_id: "run_5530",
    trace_id: "trace_0a71",
    latency_ms: 58,
  },
];

export default function Example() {
  return (
    <AuditLog
      title="Audit log"
      events={events}
      now="2026-01-14T18:00:00Z"
      height={460}
    />
  );
}
